### ISSUE TITLE
mech_ec.c:1359: undefined reference to `BN_bn2binpad'

### ISSUE THREAD

**Issue by kingaj12** [opencryptoki/opencryptoki#368]
During make, I received the error:

    /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: usr/lib/common/.libs/opencryptoki_stdll_libpkcs11_cca_la- mech_ec.o: in function `ec_uncompress_public_key':
    /home/kingaj/Downloads/opencryptoki/usr/lib/common/mech_ec.c:1359: undefined reference to `BN_bn2binpad'
    collect2: error: ld returned 1 exit status

My system configuration is:

    $ cat /etc/os-release
    NAME="Red Hat Enterprise Linux Server"
    VERSION="7.9 (Maipo)"

    $ g++ --version
    g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

    $ openssl version
    OpenSSL 3.0.0-alpha11 28 jan 2021 (Library: OpenSSL 3.0.0-alpha11 28 jan 2021)

I tried commenting out lines 32 and 58 in `./usr/lib/common/mech_ec.c` but this generated a lot of compile errors.

**Comment by ifranzki** [comment]
Older OpenSSL versions do not provide `BN_bn2binpad`, but you seem to run with OpenSSL 3.0.0-alpha11. I would assume that it does provide `BN_bn2binpad`... Maybe the OpenSSL version detection using `OPENSSL_VERSION_NUMBER` does no longer work with OpenSSL 3.0?

@p-steuer Can you please take a look?

**Comment by kingaj12** [comment]
Update:  I had no problems building on my WSL installation of Ubuntu 20.04.  Could be an RHEL issue (have lots of those :(

**Comment by kingaj12** [comment]
For WSL/Ubuntu I had to add `/usr/local/lib/opencryptoki` to my load library configuration in order to find the library.  But now I have the problem:

    $ pkcsconf -i
    Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)

**Comment by ifranzki** [comment]
> Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)

Enable the trace and see if it shows any errors:
`export OPENCRYPTOKI_TRACE_LEVEL=4`
The trace goes to `/var/log/opencryptoki/trace.<pid>`, or `/usr/local/var/log/opencryptoki/trace.<pid>` if you install it to /usr/local.

Also make sure you run `ldconfig` after `make install`.

**Comment by kingaj12** [comment]
Hi - yes the ldconfig helped a lot.  Thanks!
